import '../globals.css'

import { Italiana, EB_Garamond as EbGaramond } from 'next/font/google'

export const metadata = {
  title: 'Monte & Cavalcante | Landing Page',
  description: 'Generated by Next.js',
}

const italiana = Italiana({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-italiana',
})

const garamond = EbGaramond({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-garamond',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${italiana.variable} ${garamond.variable} bg-secondary`}
      >
        {children}
      </body>
    </html>
  )
}
